[project]
name = "sendthephotos"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "authlib>=1.5.2",
    "flask>=3.1.0",
    "requests>=2.32.3",
]

[dependency-groups]
dev = [
    "python-dotenv>=1.1.0",
]
